# Generated by Django 5.0.1 on 2024-01-17 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('pincode', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('reader_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=3)),
                ('Address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.address')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FirstApp.book')),
            ],
        ),
    ]
